# Generated by Django 4.0.3 on 2022-05-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0003_persona_alter_article_options_alter_category_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('authors', models.CharField(max_length=255)),
                ('average_rating', models.FloatField()),
                ('isbn', models.CharField(max_length=150)),
                ('isbn13', models.CharField(max_length=150)),
                ('languaje_code', models.CharField(max_length=10)),
                ('num_pages', models.IntegerField()),
                ('ratings_count', models.BigIntegerField()),
                ('text_review_count', models.BigIntegerField()),
                ('publicacion_date', models.DateField(auto_now=True)),
                ('publisher', models.CharField(max_length=150)),
            ],
        ),
    ]
